= PRBX SimpleCPU Instruction Set Simulator

This project is to implement the mjf5.011 project at the University of York.

== Outline

The SimpleCPU ISS is a teaching tool designed to help students (or anyone) who is struggling to understand how CPU
execute instructions. Anyone could learn what an instruction does when manually calculating something but how does a
CPU interpret that.

The basic structure is the different sections of the CPU is held within the `sections` folder, this has been designed
as simply as possible to understand the logic for anyone who wishes to learn the data flow.

== Instructions

Below is a list of instructions that have been implemented, this is based on the SimpleCPU 1a architecture.

Instructions are 16-bits long and are comprised on three sections, the most significant 4-bits is the instruction.
The next 4-bits are not used in this architecture as this is reserved in future iterations.

The final 8-bits are currently one of two things: K is a constant, and the value is directly added to the Accumulator,
A is the address of a memory location where it will be moved into the Accumulator.

The exception to this is Jumps where the data at the address is stored in the Program Counter.

=== MOVE
[%hardbreaks]
`MOVE   0000 XXXX KKKKKKKK`
MOVE instruction moves the value of `KKKKKKKK` into the ACC
`ACC <- KK`

=== ADD
[%hardbreaks]
`ADD    0001 XXXX KKKKKKKK`
ADD instruction adds the value of `KKKKKKKK` with the current value of the ACC and moves that to the ACC
_Please note that the Z (zero) flag is not set but is determined by the output of the ACC_
`ACC <- ACC + KK`

=== SUB
[%hardbreaks]
`SUB    0010 XXXX KKKKKKKK`
SUB instruction subtracts the value of `KKKKKKKK` from the current value of the ACC and moves that to the ACC
_Please note that the Z (zero) flag is not set but is determined by the output of the ACC_
`ACC <- ACC - KK`

=== AND
[%hardbreaks]
`AND    0011 XXXX KKKKKKKK`
AND instruction bitwise ands the value of `KKKKKKKK` and the current value of the ACC and moves that to the ACC
_Please note that the Z (zero) flag is not set but is determined by the output of the ACC_
`ACC <- ACC & KK`

=== LOAD
[%hardbreaks]
`LOAD   0100 XXXX AAAAAAAA`
LOAD instruction moves the lower 8-bits of the memory location `AAAAAAAA` into the ACC
e.g. `M[123]=9` so by the end of the execution `ACC=9`

=== STORE
[%hardbreaks]
`STORE  0101 XXXX AAAAAAAA`
STORE instruction moves the 8-bit value from the ACC to the memory location `AAAAAAAA`
e.g. `ACC=11` so by the end of the execution `M[121]=11`

=== ADDM
`ADDM   0110 XXXX AAAAAAAA` +
ADDM instruction adds the value from memory address `AAAAAAAA` with the current value of the ACC and moves
that to the ACC +
_Please note that the Z (zero) flag is not set but is determined by the output of the ACC_ +
`ACC <- ACC + M[AA]`

=== SUBM
`SUBM   0111 XXXX AAAAAAAA` +
SUBM instruction subtracts the value from memory address `AAAAAAAA` with the current value of the ACC
and moves that to the ACC +
_Please note that the Z (zero) flag is not set but is determined by the output of the ACC_ +
`ACC <- ACC - M[AA]`

=== JUMPU
[%hardbreaks]
`JUMPU  1000 XXXX AAAAAAAA`
JUMPU instruction is an unconditional jump to memory location `AAAAAAAA` by putting the value of `AAAAAAAA` into the PC
`PC <- AA`

=== JUMPZ
`JUMPZ  1001 XXXX AAAAAAAA` +
JUMPZ instruction is a conditional jump to memory location `AAAAAAAA`
if the zero flag is set `Z = 1` by putting the value of `AAAAAAAA` into the PC +
`PC <- IF Z=1 THEN PC <- AA ELSE PC <- PC + 1`

=== JUMPNZ
`JUMPNZ 1010 XXXX AAAAAAAA` +
JUMPNZ instruction is a conditional jump to memory location `AAAAAAAA`
if the zero flag is unset `Z = 0` by putting the value of `AAAAAAAA` into the PC +
`PC <- IF Z=0 THEN PC <- AA ELSE PC <- PC + 1`

== Micro Instructions

Micro instructions are the building blocks of any instruction that exists in a system.
Each of the preceding instructions were comprised of a variety of micro instructions across multiple cycles.

Instructions sometimes require multiple cycles to completely execute an instruction where data needs to be moved around
in a more complex manor.

This means that the "Fetch, Decode and Execute" cycle can sometimes be more of a "Fetch, Decode, multiple Execute"

SimpleCPU 1a has a 12-bit output control bus

=== PC_EN
[%hardbreaks]
`PC_EN` - Program Counter enable = `0B100000000000`
The Program Counter outputs to the Address Bus

=== PC_LD
[%hardbreaks]
`PC_LD` - Program Counter load = `0B010000000000`
The Program Counter outputs to the Address Bus mux

=== IR_EN
[%hardbreaks]
`IR_EN` - Instruction Register enable = `0B001000000000`
The Program Counter outputs to the Internal Bus

=== ACC_EN
[%hardbreaks]
`ACC_EN` - Accumulator enable = `0B000100000000`
The Accumulator outputs to the Data In Bus

=== ACC_CTL2
[%hardbreaks]
`ACC_CTL2` - ALU control line 2 = `0B000010000000`
The control line 2 is part of ALU control

=== ACC_CTL1
[%hardbreaks]
`ACC_CTL1` - ALU control line 1 = `0B000001000000`
The control line 1 is part of ALU control

=== ACC_CTL0
[%hardbreaks]
`ACC_CTL0` - ALU control line 0 = `0B000000100000`
The control line 0 is part of ALU control

.ALU control logic
,===
ACC_CTL2, ACC_CTL1, ACC_CTL0, OP

0,0,0,ADD
0,0,1,SUB
0,1,0,AND
0,1,1,NU
1,0,0,PASS
1,0,1,NU
1,1,0,NU
1,1,1,NU
,===
Not used is denoted by `NU`

=== ADDR_SEL
[%hardbreaks]
`ADDR_SEL` - Address mux selector = `0B000000010000`
Signal 0 passes the Program Counter to the Address Bus
Signal 1 passes the Internal Bus to the Address Bus

=== DATA_SEL
[%hardbreaks]
`DATA_SEL` - Data mux selector = `0B000000001000`
Signal 0 passes the Internal Bus to the ALU
Signal 1 passes the Data Out Bus to the ALU

=== RAM_EN
[%hardbreaks]
`RAM_EN` - RAM enable = `0B000000000100`
The RAM outputs to the Data Out Bus (not used)

=== RAM_WR
[%hardbreaks]
`RAM_WR` - RAM write enable = `0B000000000010`
The RAM accepts data in from the Data In Bus

=== ROM_EN
[%hardbreaks]
`ROM_EN` - ROM enable = `0B000000000001`
The RAM outputs to the Data Out Bus (not used)
